### PR TITLE
Fix bug in dcm discovery where zero-length resp-data can cause crash

### PR DESCRIPTION
**Pull request by JackDunham**
Fix bug in dcm discovery where zero-length resp-data can cause crash; Add "nostop" arg to dcm discovery to not stop at first item found (defaults to NOT stopping)

### CODE REVIEW

**Comment by kasperkarlsson** [comment]
The str2bool function should be removed. Cleaner code and simpler command line argument syntax can be achieved by using the built-in "store_true"/"store_false" actions in argparse instead.

**Comment by JackDunham** [comment]
Made suggested changes, re: argparse, and simplified "nostop" logic.

**Comment by kasperkarlsson** [comment]
This looks great!

Sorry for missing this before, but I just spotted one more thing - the "found_diagnostics" variable should be kept inside of dcm.py. It would be unclean to add such a module specific flag to can_actions.py. If this is fixed I will gladly merge this PR.

**Comment by JackDunham** [comment]
Hey there -- instead of moving `found_diagnostics` to dcm module, which would have meant creating a global variable (ick!!!) or using decorators (more ick!!!), I turned `found_diagnostics` into `opaque_data` dict, (initialized at constructor-time). It makes for a convenient, non-global, data-bag. Lives only as long as the CanActions object.

**Comment by kasperkarlsson** [comment]
I agree that global variables are in general quite icky. However, I consider adding an opaque dict for general-icky-module-behavior to can_actions.py to be even ickier. This would risk looking like an invite to push global state from individual modules into the CAN actions module, where it does not belong.

In the rare case that a module needs to keep track of a global state, I prefer a global variable within the module itself. This looks like a valid case for such a global variable to me :)

**Comment by JackDunham** [comment]
Hi @kasperkarlsson! Figured out a clean way to not add anything to `CanActions`, and also not need a global variable in dcm.py. Let me know what you think.

**Comment by kasperkarlsson** [comment]
This is a valid workaround for python 2.7's lack of a nonlocal statement in this scenario. A (negligible) bit more overhead than a global variable, but also a (negligible) bit less namespace pollution.

I have resorted to similar hacks myself a few times, but I am not sure whether it should be considered "better" than globally shared states or not. That being said, this solution looks clean without pushing module specific code over to can_actions.py.

Thanks a lot!

**Pull request merged**
