### PR TITLE
Padding Support for UDS and UDS_Fuzz modules

### PR DESCRIPTION
**Pull request by Cr0wTom**
Adding support for different (or no) padding to UDS and UDS_Fuzz modules with changes to the iso15765 library.

### CODE REVIEW

**Comment by kasperkarlsson** [comment]
This PR seems to break the separation of ISO 14229 protocol implementation and the modules using this protocol. Re-implementing every needed service of the protocol in each module (possibly even multiple times) may lead to differing implementations and thus inconsistency, as well as harder-to-read code.

If the goal is to make optional padding possible, this should rather be added on the transport level (ISO-15765-2 / ISO-TP) and utilized as the user the desires by the ISO 14229 protocol. I do not have the specifics of this implementation in my mind right now (and limited time to put into this during the next days), but I am of course open to a discussion regarding pros and cons of different approaches 🙂

**Comment by kasperkarlsson** [comment]
Time for a small update!

I like your idea, and I have attempted to implement a clean method of optional, caller-controlled padding for ISO-TP (which you can see in its current state in #91). I also plan to expose this (as described in my previous comment) via the UDS and UDS Fuzz modules as a next step.

This is just to let you know that I aim to get your feature idea up and running 🙂

**Comment by kasperkarlsson** [comment]
Hi there,

Are all new commits part of the PR, or is this PR your new `main` branch?

**Comment by Cr0wTom** [comment]
Sorry for this, personal branch :)

**Comment by kasperkarlsson** [comment]
No worries! Keep on hacking 🤘

**Pull request closed without merging**
