### PR TITLE
Add support for service $23 - read memory by address

### PR DESCRIPTION
**Pull request by alexdetrano**
This is basically a rewrite of https://github.com/CaringCaribou/caringcaribou/pull/79 but only focusing on the memory read code. I fixed it up and isolated the changes as discussed in that PR. I've used it extensively against real modules and it works great.

### CODE REVIEW

**Comment by kasperkarlsson** [comment]
This sounds very promising! This is just to let you know that the PR has been noticed, and I aim to review the proposed changes soon 👍

**Review by kasperkarlsson — APPROVED** [review]
All in all, this PR looks great 🎉🥇 And I am very, very happy to see the bugfix in `iso14229_1.py`! 💪 

I took the liberty of making three additional commits:
* Small formatting changes (for PEP 8 compliance)
* Implemented the NRC lookup to human readable form for applicable values defined for ReadMemoryByAddress in the ISO 14229 standard, as suggested in your TODO comment
* Broke out a magic number (`0x63`) for the service response ID, to make the code easier to read

If you think this looks good, I will be happy to merge the PR 😃

**Review by alexdetrano — COMMENTED** [review]
i love this commit! i think long term we should move this to a function/method and then anytime we get a negative response, i.e. in other UDS functions, we use it to inform the user what the decoded NRC is in the error message. but this is a great start.

**Review by alexdetrano — COMMENTED** [review]
looks good to me!

**Comment by kasperkarlsson** [comment]
FYI: I had a closer look at your suggestion and it turns out there was already a dict for `NRC value` -> `NRC name` lookup, which I had forgotten about 😅 Moved over to use this consistently in https://github.com/CaringCaribou/caringcaribou/commit/61f89a5802af586b83d1182b47ac0e6e2c0b8aa8

**Pull request merged**
